runtime: python
api_version: 1
threadsafe: true
env: flex

runtime_config:
    python_version: 3

handlers:
- url: /static
  static_dir: frontend/build/static
- url: /.*
  script: app

entrypoint: gunicorn -b :$PORT app:app
