runtime: python
api_version: 1
threadsafe: true
env: flex
instance_class: B2
manual_scaling:
  instances: 1

runtime_config:
    python_version: 3

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:123456@/addressbook?host=/cloudsql/address-book-196923:australia-southeast1:address-book-postgresql

beta_settings:
    cloud_sql_instances: address-book-196923:australia-southeast1:address-book-postgresql

handlers:
- url: /static
  static_dir: frontend/build/static
- url: /.*
  script: app

entrypoint: gunicorn -b :$PORT app:app
